import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>LangOasis</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 data-testid="cypress-title" className="text-2xl font-extrabold tracking-tight text-white sm:text-2xl">
            LangOasis
          </h1>
          <p data-testid="cypress-subtitle" className="text-white text-center text-sm md:text-md lg:text-lg max-w-md">Where you can discover and explore popular and obscure programming languages.</p>
        </div>
      </main>
    </>
  );
}
